
export const items=[
    {
        name:"Prada",
        category:"Bags"
    },
    {
        name:"Gussi",
        category:"Bags"
    },
    {
        name:"Guess",
        category:"Bags"
    },
    {
        name:"Rolex",
        category:"Watches"
    },
    {
        name:"Timex",
        category:"Watches"
    },
    {
        name:"Nike",
        category:"Sports"
    }
    ,
    {
        name:"Addidas",
        category:"Sports"
    },
    {
        name:"Atlas",
        category:"Sports"
    },
    {
        name:"Dhoop",
        category:"Sunglasses"
    },
    {
        name:"night",
        category:"Sunglasses"
    },
    {
        name:"Dark",
        category:"Sunglasses"
    }
]